### ISSUE TITLE
Create Discord server for group chat and video meetings

### ISSUE THREAD

**Issue by LionOnTheWeb** [OLLEO-DIGITAL/OLLEO-WEB#3]
# Overview
As a developer on OLLEO, I want to have a Discord server available so that I can have a general chat with the team members and join video meetings through it.

# Tasks
- [x] Create a Discord server
- [ ] Verify of meeting links can be scheduled
    - [ ] If yes, schedule a new meeting for April 9, 2023 at 9pm and add it to the Google calendar invite agenda
- [ ] Add link to Discord server in comments below

**Comment by LionOnTheWeb** [comment]
Found this that might be useful! 
https://support.discord.com/hc/en-us/articles/4409494125719-Scheduled-Events#:~:text=Schedule%20an%20event%20for%20somewhere%20else,-If%20you'd&text=1.-,Press%20on%20the%20down%20arrow%20next%20to%20your%20server's%20name,Event%20option%20from%20the%20menu.

**Comment by LionOnTheWeb** [comment]
CC @Reaper-X ☝
